// <auto-generated />
using System;
using DrugPricing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(DrugPricingContext))]
    [Migration("20260504172323_FK3")]
    partial class FK3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrugPricing.Models.DrugPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Ndc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("NdcDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NdcDescriptionLower")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("LOWER(\"NdcDescription\")", true);

                    b.HasKey("Id");

                    b.HasIndex("Ndc")
                        .IsUnique();

                    b.HasIndex("NdcDescriptionLower");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NdcDescriptionLower"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NdcDescriptionLower"), new[] { "gin_trgm_ops" });

                    b.ToTable("DrugPackages");
                });

            modelBuilder.Entity("DrugPricing.Models.FdaPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("EndMarketingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NdcExcludeFlag")
                        .HasColumnType("text");

                    b.Property<string>("NdcPackageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NdcPackageCodeStripped")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackageDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<string>("ProductNdc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SamplePackage")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartMarketingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("NdcPackageCode")
                        .IsUnique();

                    b.HasIndex("NdcPackageCodeStripped");

                    b.HasIndex("ProductId");

                    b.ToTable("FdaPackages");
                });

            modelBuilder.Entity("DrugPricing.Models.FdaProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeaSchedule")
                        .HasColumnType("text");

                    b.Property<string>("DosageFormName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndMarketingDate")
                        .HasColumnType("date");

                    b.Property<string>("LabelerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ListingRecordCertifiedThrough")
                        .HasColumnType("date");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketingCategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NdcExcludeFlag")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("NonProprietaryName")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("PharmClasses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductNdc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProprietaryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProprietaryNameSuffix")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("RouteName")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateOnly>("StartMarketingDate")
                        .HasColumnType("date");

                    b.PrimitiveCollection<string[]>("StrengthNumber")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("StrengthUnit")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("FdaProducts");
                });

            modelBuilder.Entity("DrugPricing.Models.NadacImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NadacImports");
                });

            modelBuilder.Entity("DrugPricing.Models.NadacPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("ClassificationForRateSetting")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateOnly?>("CorrespondingGenericEffectiveDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("CorrespondingGenericNadacPerUnit")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.PrimitiveCollection<int[]>("ExplanationCode")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("IsOtc")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NadacPerUnit")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)");

                    b.Property<string>("Ndc")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("NdcDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NdcDescriptionLower")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("LOWER(\"NdcDescription\")", true);

                    b.Property<string>("PharmacyTypeIndicator")
                        .HasColumnType("text");

                    b.Property<string>("PricingUnit")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate");

                    b.HasIndex("Ndc");

                    b.HasIndex("NdcDescriptionLower");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NdcDescriptionLower"), "gist");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NdcDescriptionLower"), new[] { "gist_trgm_ops" });

                    b.HasIndex("Ndc", "EffectiveDate", "AsOfDate")
                        .IsUnique();

                    b.ToTable("NadacPrices");
                });

            modelBuilder.Entity("DrugPricing.Models.FdaPackage", b =>
                {
                    b.HasOne("DrugPricing.Models.FdaProduct", "FdaProduct")
                        .WithMany("FdaPackages")
                        .HasForeignKey("ProductId")
                        .HasPrincipalKey("ProductId");

                    b.Navigation("FdaProduct");
                });

            modelBuilder.Entity("DrugPricing.Models.NadacPrice", b =>
                {
                    b.HasOne("DrugPricing.Models.FdaPackage", "FdaPackage")
                        .WithMany("NadacPrices")
                        .HasForeignKey("Ndc")
                        .HasPrincipalKey("NdcPackageCodeStripped");

                    b.Navigation("FdaPackage");
                });

            modelBuilder.Entity("DrugPricing.Models.FdaPackage", b =>
                {
                    b.Navigation("NadacPrices");
                });

            modelBuilder.Entity("DrugPricing.Models.FdaProduct", b =>
                {
                    b.Navigation("FdaPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
